# Configuration on how ReadTheDocs (RTD) builds our documentation
# ref: https://readthedocs.org/projects/jupyterhub/
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
#
version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

python:
  install:
    - path: .
    - requirements: docs/requirements.txt

formats:
  # Adding htmlzip enables a Downloads section in the rendered website's RTD
  # menu where the html build can be downloaded. This doesn't require any
  # additional configuration in docs/source/conf.py.
  #
  - htmlzip
